jozefntes/meal-plan-gen-app

server/package-lock.json
server/package.json

This pull request includes updates to the `@google/generative-ai` dependency in the `server` package. The most important changes are as follows:
Dependency updates:
* [`server/package-lock.json`](diffhunk://#diff-be330df323f72d45d073e311befe92984fad9846bb7e982261d702d805c14053L12-R12): Updated the version of `@google/generative-ai` from `0.21.0` to `0.22.0`, including changes to the resolved URL and integrity hash. [[1]](diffhunk://#diff-be330df323f72d45d073e311befe92984fad9846bb7e982261d702d805c14053L12-R12) [[2]](diffhunk://#diff-be330df323f72d45d073e311befe92984fad9846bb7e982261d702d805c14053L32-R34)
* [`server/package.json`](diffhunk://#diff-da00458cdaeaea2314cb0e0101c85130593048072ada62de01727958c5d6ca37L16-R16): Updated the version of `@google/generative-ai` from `0.21.0` to …

Update @google/generative-ai dependency to version 0.22.0

---

client/package-lock.json
client/package.json

This pull request includes changes to add a new dependency to the project. Specifically, the `@react-oauth/google` package has been added to the `client` project.
Dependency additions:
* [`client/package.json`](diffhunk://#diff-1846122c2c83a486a3693f7966aa522c34cf489f674185c4da0d9221683fd81fR13): Added `@react-oauth/google` version `^0.12.1` to the dependencies.
* [`client/package-lock.json`](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR11): Added `@react-oauth/google` version `0.12.1` with its resolved URL, integrity hash, license, and peer dependencies. [[1]](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR11) [[2]](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR1075-R1084)

SCRUM-38 Add @react-oauth/google dependency to client package

---

server/server.js

This pull request includes changes to the `server/server.js` file to remove the `verifyToken` middleware from certain API endpoints.
Security adjustments:
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L82-R82): Removed the `verifyToken` middleware from the `GET /api/recipes/:uid` endpoint.
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L113-R113): Removed the `verifyToken` middleware from the `POST /api/generate_recipe` endpoint.

Remove token verification from recipe API endpoints

---

client/vercel.json

This pull request includes a configuration change to the `client/vercel.json` file to set up URL rewrites.
Configuration change:
* [`client/vercel.json`](diffhunk://#diff-855441862413f6eddef861a904efa430cedc3387cc88f6fb6157bed17a65b685R1-R8): Added a rewrite rule to redirect all paths to `index.html`.

SCRUM-54 Add Vercel configuration for URL rewrites to serve index.html

---

client/src/Home.jsx
client/src/components/MealCard.jsx
client/src/components/MealGroup.jsx

This pull request includes several changes to the `client/src` files to update how image data is handled. The most important changes are related to replacing the `imageURL` property with the `image` property and updating the way images are rendered.
Changes to image handling:
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L99-R105): Updated the `MealCard` component to use the `image` property instead of `imageURL`.
* [`client/src/components/MealCard.jsx`](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66adce1aae3bdfL7-R7): Replaced the `imageURL` property with `image` and updated the `backgroundStyle` to use a base64 encoded image URL. [[1]](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66a …

SCRUM-58 Refactor MealCard and MealGroup components to use base64 image data instead of imageURL

---

client/src/Home.css
client/src/MealPlanGenerator.css

This pull request includes changes to the CSS files to adjust the layout margins for better alignment and consistency.
Layout adjustments:
* [`client/src/Home.css`](diffhunk://#diff-3b1a9da07623e6c614d6f215bddee90c945a731e686938b8b0009b5523e3bf9dL3-R3): Changed the `.content` class margin-left from 325px to 280px.
* [`client/src/MealPlanGenerator.css`](diffhunk://#diff-7a7b0565044d4b893d86a4818618f71aa2ac16545de9f13e57fce07814f9bb41L2-R2): Changed the `.generate-page` class margin-left from 325px to 280px.

SCRUM-63 Reduce left margin in content and meal plan generator styles

---

client/src/MealPlanGenerator.jsx

This pull request includes several updates to the `MealPlanGenerator` component to improve user experience by adding loading states and navigation. The most important changes include importing the `page` library for navigation, adding a loading state, and updating the button to reflect the loading state.
Enhancements to user experience:
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00R3): Imported the `page` library to handle navigation after generating a meal plan.
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00R26): Introduced a `loading` state to manage the loading indicator when generating a meal plan.
* …

SCRUM-75 Add loading state to meal plan generation button

---

client/src/MealInfo.jsx

This pull request includes a change to the `client/src/MealInfo.jsx` file. The change involves renaming the default export function from `MealPlanGenerator` to `MealInfo`.
* [`client/src/MealInfo.jsx`](diffhunk://#diff-dd264326910cb8b5a6d80b7edcf1d011b569b5974af8da2ed13db83ee1df5fa6L11-R11): Renamed the default export function from `MealPlanGenerator` to `MealInfo`.

SCRUM-77 Fix MealInfo component naming

---

server/server.js

This pull request includes a small but important change to the `server/server.js` file. The change ensures that the newly created recipe document's ID is assigned to the `recipe` object after saving it to the database.
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R436): Added a line to assign the document ID to the `recipe` object after saving it to the database.

SCRUM-78 Add recipe ID to generated recipe response

---

client/src/Home.jsx
client/src/components/MealCard.jsx

This pull request includes changes to the `client/src/Home.jsx` and `client/src/components/MealCard.jsx` files to rename the `groupMeal` property to `mealGroup`.
Renaming property for consistency:
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L174-R179): Changed `groupMeal` to `mealGroup` in the sorting function and `MealCard` component mapping.
* [`client/src/components/MealCard.jsx`](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66adce1aae3bdfL7-R7): Updated the `MealCard` component to use `mealGroup` instead of `groupMeal` in the property list and `getMealLabel` function call. [[1]](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66adce1aae3bdfL7-R7) …

SCRUM-94 Rename groupMeal to mealGroup for consistency in meal data handling

---

client/src/components/CreateRecipe.css

This pull request includes changes to the `CreateRecipe.css` file to improve the styling of the `CreateRecipe` component. The most important changes include updating the background color to use a CSS variable and enhancing the styling of the textarea element.
Styling improvements:
* [`client/src/components/CreateRecipe.css`](diffhunk://#diff-ea34ec18fb7cb2ce8bf2f16090046272e6d868106322c1d837e6db6828ec4a8aL18-R18): Changed the background color of the `CreateRecipe` component to use a CSS variable `--background-color` instead of a hardcoded white color.
* [`client/src/components/CreateRecipe.css`](diffhunk://#diff-ea34ec18fb7cb2ce8bf2f16090046272e6d868106322c1d837e6db6828ec4a8aL39-R44): Updated the textarea element within the `.form-group` class to include a margin at the bottom, use a CSS …

SCRUM-91 Fix CreateRecipe modal styling

---

server/server.js

This pull request introduces a new endpoint to delete a specific recipe by its document ID in the `server/server.js` file. The most important change is the addition of the `DELETE /api/recipe/:id` endpoint, which includes error handling and user verification.
New endpoint addition:
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R434-R465): Added a new `DELETE /api/recipe/:id` endpoint to delete a specific recipe by its document ID. This includes checking for the existence of the recipe, verifying the user ID, and handling errors appropriately.

SCRUM-93 Add endpoint to delete a recipe by ID with authorization checks

---

server/package-lock.json

This pull request includes an update to the `axios` package in the `server/package-lock.json` file. The version has been upgraded from 1.7.9 to 1.8.4. 
* [`server/package-lock.json`](diffhunk://#diff-be330df323f72d45d073e311befe92984fad9846bb7e982261d702d805c14053L1157-R1159): Updated `axios` version from 1.7.9 to 1.8.4 to ensure the latest features and security updates are included.

SCRUM-103 Update axios dependency to version 1.8.4 in package-lock.json

---

server/server.js

This pull request introduces a new endpoint to the `server.js` file for replacing a meal in a user's meal plan. The endpoint includes several validation checks and error handling to ensure the integrity of the meal plan update process.
Key changes:
* Added a new POST endpoint `/api/replace_recipe` to replace a meal in a user's meal plan (`server/server.js`).
* Validates required fields (`uid`, `date`, `currentMealId`, `newMealId`).
* Ensures the new meal ID is different from the current meal ID.
* Checks the date format to be `YYYY-MM-DD`.
* Verifies the existence of the new meal ID in the `recipes` collection.
* Updates the meal plan in the `plans` collection if all checks pass.
These changes enhance the functionality of the server by allowing users to update their meal plans with new …

Add API endpoint to replace a recipe in a meal plan with validation checks

---

client/src/Home.jsx
client/src/components/MealCard.jsx
client/src/components/ReplaceRecipeModal.jsx
client/src/utils/recipeUtils.js

This pull request introduces a new feature to enhance the recipe replacement functionality by adding an inverted index for efficient recipe search based on ingredients. The most important changes include the addition of the inverted index state, the implementation of the `buildInvertedIndex` function, and the use of this index in the `ReplaceRecipeModal` component to find similar recipes.
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R34): Added state `invertedIndex` and implemented `buildInvertedIndex` function to create an index of ingredients to recipe IDs. The index is updated whenever the `recipes` state changes. [[1]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R34) …

SCRUM-121 Add inverted index for recipe ingredient matching

---

client/src/Home.jsx
client/src/components/MealCard.jsx
server/server.js

This pull request includes several changes to the `Home` and `MealCard` components to improve the handling of meal instances and their unique identifiers. The most important changes include updating the `handleMealDone` function, adding a unique `mealInstanceId` to each meal, and refactoring the `MealCard` component to use the `meal` object directly.
Updates to meal instance handling:
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L78-R83): Modified the `handleMealDone` function to use `mealInstanceId` instead of `id` for toggling the meal's done state.
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R133-R139): Added a unique `mealInstanceId` to each meal within the …

SCRUM-132 Refactor Home component to not use mealGroup

---

client/src/components/MealGroup.jsx
client/src/components/RecipeGrid.jsx

This pull request includes changes to the `MealGroup` and `RecipeGrid` components to simplify the code and improve maintainability. The most important changes include removing the `MealCard` import and refactoring how recipes are displayed in the `MealGroup` component, as well as modifying the `RecipeGrid` component to pass the entire `recipe` object to `MealCard`.
Code simplification and refactoring:
* [`client/src/components/MealGroup.jsx`](diffhunk://#diff-4361ac94da04fb7f0f479b4c925a1a7b35e9e7455201eff0d314bd00c6553c1aL1): Removed the `MealCard` import since it is no longer used.
* [`client/src/components/MealGroup.jsx`](diffhunk://#diff-4361ac94da04fb7f0f479b4c925a1a7b35e9e7455201eff0d314bd00c6553c1aL13): Removed the `onDeleteRecipe` prop from the `MealGroup` component as it is no …

SCRUM-133 Refactor MealGroup and RecipeGrid components to simplify recipe rendering and remove unused props

---

server/server.js

This pull request simplifies the `generate_recipe` API endpoint by removing the `mealGroup` parameter, which is no longer required for recipe generation. The changes include updates to the request body validation and the recipe object construction.
* Removed the `mealGroup` parameter from the request body and updated the validation logic to no longer check for its presence. (`server/server.js`, [server/server.jsL385-R387](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L385-R387))
* Eliminated the assignment of the `mealGroup` property to the `recipe` object, as it is no longer part of the API's functionality. (`server/server.js`, [server/server.jsL435](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L435))

SCRUM-144 Refactor generate_recipe endpoint to remove mealGroup requirement and simplify validation

---

client/src/components/CreateRecipe.jsx

This pull request simplifies the `CreateRecipe` component in `client/src/components/CreateRecipe.jsx` by removing the `mealGroup` prop and all related functionality. The changes streamline the component's code and reduce unnecessary form fields.
* Removed the `mealGroup` prop from the `CreateRecipe` component's props. (`[client/src/components/CreateRecipe.jsxL19-R19](diffhunk://#diff-f28e439c1e9a1d50f388925191b090686a1a9486e391e179011a4f181c16d901L19-R19)`)
* Eliminated the logic for retrieving and parsing the `mealGroup` value from the DOM. (`[client/src/components/CreateRecipe.jsxL54-L56](diffhunk://#diff-f28e439c1e9a1d50f388925191b090686a1a9486e391e179011a4f181c16d901L54-L56)`)
* Removed the `mealGroup` field from the payload sent in the POST request. …

SCRUM-145 Remove mealGroup prop and associated form elements from CreateRecipe component

---

client/src/components/Sidenav.jsx

This pull request makes changes to the `Sidenav.jsx` file to remove the unused `SettingIcon` import and the corresponding "Settings" navigation item from the sidebar. It also includes minor formatting adjustments to improve code readability.
* [`client/src/components/Sidenav.jsx`](diffhunk://#diff-cf4686b80d69f6d3f89d133171d85a3e759ebb3752804f8aa21e7f4ab438e577L9): Removed the import for `SettingIcon` as it is no longer used in the component.
* [`client/src/components/Sidenav.jsx`](diffhunk://#diff-cf4686b80d69f6d3f89d133171d85a3e759ebb3752804f8aa21e7f4ab438e577L81-L92): Removed the "Settings" navigation item from the sidebar, including its associated icon and label.
* [`client/src/components/Sidenav.jsx`](diffhunk://#diff-cf4686b80d69f6d3f89d133171d85a3e759ebb3752804f8aa21e7f4ab438e577L81 …

SCRUM-147 Remove Settings tab from the sidebar
