- .gitignore
- package-lock.json
- server/gemini-start.js
- server/package-lock.json
- server/package.json
- server/src/server.js
to try out the Gemini, get your API key from Gemini studio, make a env file in the server file, and add the variable API_KEY = "YOUR_API_KEY". After all that run node gemini-start.js in the console inside the server directory
> Implementation of Gemini

- server/package-lock.json
- server/package.json
- server/server.js
This pull request includes significant changes to the `server` directory, focusing on module type configuration, dependency updates, and the transition from CommonJS to ES Modules. The most important changes include adding the module type to `package.json`, removing unused dependencies, and updating `server.js` to use ES module syntax.
Configuration updates:
* [`server/package.json`](diffhunk://#diff-da00458cdaeaea2314cb0e0101c85130593048072ada62de01727958c5d6ca37R2): Added `"type": "module"` to specify that the project uses ES Modules.
Dependency updates:
* [`server/package.json`](diffhunk://#diff-da00458cdaeaea2314cb0e0101c85130593048072ada62de01727958c5d6ca37L20-R21): Removed `sqlite`, `sqlite3`, and their related dependencies as they are no longer used.
Code modernization:
* …
> SCRUM-28 Update server to use ES modules and remove sqlite3 dependency

- server/server.js
This pull request includes enhancements to the recipe generation API endpoint in `server/server.js`. The changes introduce new fields to the request body, improve error handling, and add functionality to save generated recipes to a database.
Enhancements to recipe generation API:
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L46-R47): Added `uid` and `mealGroup` fields to the request body for the recipe generation API endpoint.
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L72-R99): Improved parsing of the generated recipe to handle both array and object formats.
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L72-R99): …
> SCRUM-27 Store AI generated recipe in the firestore db

- client/public/icons/noShowPassword.svg
- client/public/icons/showPassword.svg
- client/src/App.jsx
- client/src/components/SignIn.jsx
- client/src/components/SignUp.css
- client/src/components/SignUp.jsx
- client/src/main.jsx
Added:
SignUp.jsx
SignIn.jsx
SignUp.css
Icons + Photo
> Sign up page

- client/src/components/SignIn.jsx
- client/src/components/SignUp.jsx
This pull request includes several changes to the `SignIn` and `SignUp` components in the `client/src/components` directory. The changes focus on code formatting, consistency, and minor improvements to the user interface.
Code formatting and consistency:
* [`client/src/components/SignIn.jsx`](diffhunk://#diff-99e298d84b810ef81687151940075f77f4b9a20e9dec87702f5f2de5bb2eea6cL1-R7): Updated import statements to use double quotes and added semicolons for consistency. Adjusted indentation and spacing for better readability.
* [`client/src/components/SignUp.jsx`](diffhunk://#diff-5743e19f92d51e5c94028270dcf7ebebe04b255ad5d058a626999b2222490f0eL1-L11): Updated import statements to use double quotes and added semicolons for consistency. Adjusted indentation and spacing for better readability. …
> SCRUM-39 Fix signup image path in SignUp component and format Signin

- client/src/App.jsx
This pull request includes changes to the `client/src/App.jsx` file to add new routes and components for user authentication. The most important changes include importing the `SignUp` and `SignIn` components, adding new routes for sign-in and registration, and updating the component rendering logic to include these new routes.
Changes to user authentication:
* [`client/src/App.jsx`](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR6-R25): Imported `SignUp` and `SignIn` components.
* [`client/src/App.jsx`](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR6-R25): Added new routes for `/signin` and `/register` in the `useEffect` hook.
* [`client/src/App.jsx`](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c672 …
> SCRUM-33 Add SignIn and SignUp routes and components to App

- server/package-lock.json
- server/package.json
- server/server.js
This pull request includes updates to the `server` package to replace the Firebase client SDK with the Firebase Admin SDK. The main changes involve modifying the `server/server.js` file and updating dependencies in `server/package.json`.
Key changes include:
* Added `firebase-admin` to `server/package.json` to replace the Firebase client SDK.
* Replaced Firebase client imports with Firebase Admin SDK imports in `server/server.js`.
* Removed Firebase client configuration and initialization, and added Firebase Admin SDK initialization using a service account.
* Updated Firestore query to use Firebase Admin SDK methods in the `/api/recipes/:uid` endpoint.
* Updated Firestore document addition to use Firebase Admin SDK methods in the `/api/generate_recipe` endpoint.
> SCRUM 40 - Add firebase-admin SDK and refactor server code to use it

- server/server.js
This pull request includes changes to add Firebase ID token verification middleware and apply it to specific API routes in the `server/server.js` file.
Authentication and Authorization:
* Added `verifyToken` middleware to verify the Firebase ID token from the request headers. This middleware checks for the presence of a Bearer token, verifies it using Firebase Admin SDK, and attaches the decoded token to the request object.
* Applied the `verifyToken` middleware to the `GET /api/recipes/:uid` route to ensure that only authenticated users can access this endpoint.
* Applied the `verifyToken` middleware to the `POST /api/generate_recipe` route to ensure that only authenticated users can generate recipes.
> SCRUM 37 - Authenticate user

- client/src/components/Sidenav.jsx
- client/src/components/SignIn.jsx
- client/src/components/SignUp.jsx
- client/src/firebase.js
This pull request introduces Firebase authentication to the application, including sign-in, sign-up, and sign-out functionalities. The changes span multiple components to integrate Firebase and handle authentication processes.
* [`client/src/firebase.js`](diffhunk://#diff-874dbf3bc6835048ef48f8e8631b735b4f11a4a32afcd61846f9c26e4fcf535aR1-R16): Added Firebase initialization and configuration, including exporting `auth` and `googleProvider` for authentication purposes.
* [`client/src/components/SignIn.jsx`](diffhunk://#diff-99e298d84b810ef81687151940075f77f4b9a20e9dec87702f5f2de5bb2eea6cR2-R3): Integrated Firebase email/password and Google sign-in methods, including error handling and UI updates for Google sign-in. [[1]](diffhunk://#diff-99e298d84b810ef81687151940075f77f4b9a20e9dec87702f5f2d …
> SCRUM-41 Implement Firebase authentication in SignIn and SignUp components

- client/src/MealPlanGenerator.jsx
- client/src/components/MealGroup.jsx
This pull request includes changes to improve the handling of empty recipe lists in the meal planning components. The most important changes include adding checks for non-empty recipe arrays before attempting to filter or map through them.
Improvements to handling empty recipe lists:
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00L62-R89): Added checks to ensure `recipes` array is non-empty before filtering based on `mealGroup` for each meal type.
* [`client/src/components/MealGroup.jsx`](diffhunk://#diff-4361ac94da04fb7f0f479b4c925a1a7b35e9e7455201eff0d314bd00c6553c1aL20-R21): Added a check to ensure `recipes` array is non-empty before mapping through the recipes to display them.
> SCRUM-50 Add conditional rendering for recipes in MealPlanGenerator and MealGroup Components

- client/src/MealPlanGenerator.jsx
- client/src/components/CreateRecipe.jsx
This pull request introduces several changes to the authentication and recipe handling in the application. The most important changes include integrating Firebase authentication for fetching and creating recipes, and modifying the redirection paths after user sign-in or sign-up.
Authentication integration:
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00R2): Integrated Firebase authentication to fetch recipes specific to the authenticated user by adding an `Authorization` header with the user's ID token. [[1]](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00R2) [[2]](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00L21-R51)
* …
> SCRUM-48 Refactor code in MealPlanGenerator and CreateRecipe Components to use uid when making calls to the backend

- server/server.js
This pull request includes a change to the `server/server.js` file to simplify the user ID validation logic in the `/api/recipes/:uid` endpoint.
* Simplified the validation logic by removing the unnecessary parsing of `uid` and directly checking if `uid` is present.
> SCRUM-52 Allow UID to be a string

- server/server.js
This pull request includes changes to the `server/server.js` file to enhance the security of API endpoints by adding token verification middleware.
Security enhancements:
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L82-R82): Added `verifyToken` middleware to the `GET /api/recipes/:uid` endpoint to ensure that only authenticated users can access recipe details.
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L109-R109): Added `verifyToken` middleware to the `POST /api/generate_recipe` endpoint to ensure that only authenticated users can generate new recipes.
> SCRUM-49 Add token verification to recipe API endpoints

- client/src/App.jsx
- client/src/components/ProtectedRoute.jsx
- client/src/hooks/useAuth.js
This pull request introduces authentication protection for specific routes in the application. The changes include the addition of a `ProtectedRoute` component and a custom `useAuth` hook to manage user authentication state.
Authentication enhancements:
* [`client/src/App.jsx`](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR8): Added `ProtectedRoute` component to wrap `Home` and `MealPlanGenerator` routes, ensuring they are only accessible to authenticated users. [[1]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR8) [[2]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aL22-R32)
New components and hooks:
* [`client/src/components/ProtectedRoute.jsx`](diffhunk://#diff-b5c96bfce482c6d4c3c4 …
> SCRUM-45 Non-signed in user should not be able to go to any page other than SignUp/SignIn

- server/server.js
This pull request introduces several enhancements to the `server/server.js` file, including the integration of the Hugging Face Inference API, the addition of image generation for recipes, and an increase in server timeout. Below are the key changes:
Integration of Hugging Face Inference API:
* Added import for `HfInference` from `@huggingface/inference` to enable the use of Hugging Face's services.
* Initialized `HfInference` with the Hugging Face API key from environment variables.
Image generation for recipes:
* Implemented image generation using the `textToImage` method from `HfInference`, converting the resulting image to a base64 string, and attaching it to the recipe object.
Server configuration:
* Increased the server timeout to 5 minutes to accommodate longer processing times.
> SCRUM-56 Add image generation for recipes using Hugging Face API

- server/package-lock.json
- server/package.json
This pull request includes updates to the `server/package.json` and `server/package-lock.json` files to add a new dependency. The most important changes include the addition of the `@huggingface/inference` package and its associated dependencies.
Dependency updates:
* [`server/package.json`](diffhunk://#diff-da00458cdaeaea2314cb0e0101c85130593048072ada62de01727958c5d6ca37R18): Added `@huggingface/inference` version `^3.5.1` to the dependencies.
* [`server/package-lock.json`](diffhunk://#diff-be330df323f72d45d073e311befe92984fad9846bb7e982261d702d805c14053R13): Added `@huggingface/inference` version `3.5.1` and its dependencies, including `@huggingface/tasks` version `0.17.1`. [[1]](diffhunk://#diff-be330df323f72d45d073e311befe92984fad9846bb7e982261d702d805c14053R13) …
> SCRUM-59 Add @huggingface/inference dependency

- client/src/MealPlanGenerator.jsx
- client/src/components/MealGroup.css
- client/src/components/MealGroup.jsx
This pull request introduces several changes to the `MealPlanGenerator` and `MealGroup` components to enhance the functionality of selecting recipes for different meal groups. The most important changes include adding state management for selected recipes, implementing a handler for recipe selection, and updating the `MealGroup` component to support the new selection functionality.
Enhancements to recipe selection:
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00R19-R24): Added a new state `selectedRecipes` to manage selected recipes for breakfast, lunch, dinner, and snacks. Implemented the `handleSelectRecipe` function to update the state based on user interactions. …
> SCRUM-64 Add recipe selection functionality to MealPlanGenerator and MealGroup components

- server/server.js
This pull request to `server/server.js` includes a small change to the API endpoint for generating recipes. The change adds a new property to the `nutrition` object in the response.
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R134): Added `calories` property to the `nutrition` object in the response of the `/api/generate_recipe` endpoint.
> SCRUM-60 Add calories field to recipe nutrition object

- client/src/App.jsx
- client/src/MealInfo.css
- client/src/MealInfo.jsx
This pull request introduces a new feature to display detailed meal information in the application. The changes include adding a new route, creating a new component for meal information, and styling the component. The most important changes are summarized below:
* [`client/src/App.jsx`](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR8): Added a new route `/recipe/:id` to handle displaying meal information and integrated the new `MealInfo` component within a protected route. [[1]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR8) [[2]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR19-R21) [[3]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR39-R43)
* …
> SCRUM-46 Add MealInfo component and routing for recipe details

- client/src/MealInfo.jsx
This pull request includes several changes to the `MealInfo.jsx` file to improve error handling and user experience by adding a loading state and redirecting to the home page when an error occurs. The most important changes are as follows:
Error handling and user experience improvements:
* Added `loading` state and a loading indicator to provide feedback to users while data is being fetched. [[1]](diffhunk://#diff-dd264326910cb8b5a6d80b7edcf1d011b569b5974af8da2ed13db83ee1df5fa6R13) [[2]](diffhunk://#diff-dd264326910cb8b5a6d80b7edcf1d011b569b5974af8da2ed13db83ee1df5fa6R57-R74)
* Implemented redirection to the home page using `page("/")` when a fetch error occurs or when no user is signed in.
* Modified the rendering logic to check for the `meal` object before accessing its properties, …
> SCRUM-65 Add loading state and improve error handling in MealPlanGenerator

- client/src/App.jsx
- client/src/MealInfo.jsx
- client/src/components/Forbidden.jsx
This pull request introduces a new "Forbidden" component and updates the routing logic to handle forbidden access scenarios. The most important changes include adding the `Forbidden` component, updating the `App` component to include the new route, and modifying the `MealInfo` component to handle 403 errors.
* [`client/src/App.jsx`](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR10): Added `Forbidden` component import and updated the routing logic to include a new "/forbidden" route. Added a conditional rendering for the "forbidden" route within the `App` component. [[1]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR10) [[2]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR23-R24) …
> SCRUM-66 Add Forbidden route and component for handling access restrictions

- server/server.js
This pull request includes a change to the `server/server.js` file to enhance security by adding token verification to the `/api/generate_recipe` endpoint.
Security enhancement:
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L307-R307): Added `verifyToken` middleware to the `app.post("/api/generate_recipe", async (req, res) => {` endpoint to ensure that only authenticated users can access this API.
> SCRUM-68 Add token verification to recipe generation endpoint

- client/src/components/MealCard.jsx
This pull request includes changes to the `MealCard` component to add navigation functionality and improve event handling. The most important changes include importing the `page` module, adding a click handler for card navigation, and updating the button's click event to prevent propagation.
Navigation functionality and event handling improvements:
* [`client/src/components/MealCard.jsx`](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66adce1aae3bdfR1-R2): Imported the `page` module to enable client-side navigation.
* [`client/src/components/MealCard.jsx`](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66adce1aae3bdfR24-R46): Added `handleCardClick` function to navigate to the recipe page when the card is clicked.
* …
> SCRUM-62 Add click handler to MealCard for recipe navigation

- client/src/MealPlanGenerator.jsx
This pull request includes significant updates to the `MealPlanGenerator` component in `client/src/MealPlanGenerator.jsx`. The changes introduce new state management for error messages and add a new function to handle meal plan generation, including user authentication and validation logic.
Key changes include:
* Added a new state variable `errorMessage` to manage error messages within the component.
* Introduced the `handleGenerateMealPlan` function to handle the generation of meal plans. This function includes user authentication, validation of selected recipes, and an API call to generate the meal plan.
* Added conditional rendering for error messages, displaying them above the generate button if any errors are present.
* Updated the generate button to call `handleGenerateMealPlan` …
> SCRUM-35 Integrate Meal Plan API POST request

- server/server.js
This pull request introduces a new API endpoint to fetch meal plans for a specific user. The changes include the addition of a new route in the `server.js` file.
New API endpoint:
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R145-R184): Added a new GET endpoint `/api/meal_plans/:uid` which verifies the user token, checks if the user ID is provided, ensures the requesting user matches the user ID, and fetches meal plans from the database. It handles various error scenarios including missing user ID, forbidden access, no meal plans found, and server errors.
> SCRUM-72 Add API endpoint to fetch meal plans for a user with error handling

- server/server.js
This pull request includes a change to the `server/server.js` file to enhance the formatting of meal plan dates. The most important change is the addition of code to format the date before adding it to the `mealPlans` array.
Enhancements to date formatting:
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R175-R186): Added code to format the date to "MM/DD/YYYY" before adding it to the `mealPlans` array in the `app.get("/api/meal_plans/:uid", verifyToken, async (req, res) => {` endpoint.
> SCRUM-73 Refactor Meal Plan GET /api/meal_plans/:uid endpoint dates to use MM/DD/YYYY format

- client/src/Home.jsx
- client/src/components/MealCard.jsx
This pull request includes significant updates to the `Home` and `MealCard` components in the `client/src` directory. The changes primarily involve fetching meal plans from a server, updating state management, and modifying the structure and display of meal data.
* Added `firebase/auth` import and updated constants import to include `SERVER_URL`.
* Introduced a new state variable `mealPlans` to manage fetched meal data.
* Implemented an asynchronous function to fetch meal plans from the server using the authenticated user's ID token.
* Updated the effect that sets meal and progress data for the selected day to use the fetched `mealPlans` data.
* Replaced `time` and `name` props with `groupMeal` and `title`, and replaced individual nutrition props with a single `nutrition` prop.
* Added a …
> SCRUM-71 Integrate fetching meal plans in Home component

- client/src/components/CreateRecipe.jsx
This pull request includes changes to the `CreateRecipe` component to improve user experience by adding loading state management and error handling.
Enhancements to `CreateRecipe` component:
* Added a `loading` state using the `useState` hook to manage the loading state of the form submission.
* Updated the `createRecipe` function to set the loading state to `true` when the recipe generation starts and to `false` when it ends. [[1]](diffhunk://#diff-f28e439c1e9a1d50f388925191b090686a1a9486e391e179011a4f181c16d901R45-R47) [[2]](diffhunk://#diff-f28e439c1e9a1d50f388925191b090686a1a9486e391e179011a4f181c16d901L67-R79)
* Added error handling in the `createRecipe` function to catch and display errors if the recipe generation fails.
* Disabled the submit button and changed its text to …
> SCRUM-76 Add loading state to recipe creation and handle errors

- client/src/components/Sidenav.jsx
Routes have been added to the anchor tags for the side nav as accordingly, the only thing is change the route name for settings and profile unless you intend to keep it like that when adding the new pages in app.jsx.
> Route for sidenav

- client/src/App.jsx
- client/src/Home.jsx
- client/src/MealInfo.jsx
- client/src/MealPlanGenerator.jsx
- client/src/components/DaySelector.css
- client/src/components/EnergySummary.css
- client/src/components/MealGroup.css
- client/src/components/Sidenav.css
- client/src/components/Sidenav.jsx
- client/src/components/SignIn.jsx
- client/src/components/SignUp.css
- client/src/components/TargetSummary.css
- client/src/components/WeekSelector.css
- client/src/contexts/ThemeContext.jsx
- client/src/hooks/useTheme.js
- client/src/index.css
- client/src/main.jsx
- client/src/providers/ThemeProvider.jsx
This pull request introduces a new theme management system with light and dark modes, and updates the styles across various components to support this new feature. The most important changes include the addition of a theme context and hook, modifications to the `Sidenav` component to include a theme toggle, and updates to the CSS variables and styles to accommodate theme changes.
* [`client/src/contexts/ThemeContext.jsx`](diffhunk://#diff-0b95036d2906de1f57ce9404dc0c7c0cfb57d87f9cc9fa55681688f00eede689R1-R5): Created a new `ThemeContext` for managing theme state.
* [`client/src/hooks/useTheme.js`](diffhunk://#diff-bcd5eff7da0161fb636801c99a9acd67bbb0dd06b102ba2abd57ba74f9d76c39R1-R6): Added a custom hook `useTheme` to access the theme context.
* …
> SCRUM-86 Add Dark Mode functionality

- client/src/Home.jsx
- client/src/components/MealGroup.css
- client/src/components/MealGroup.jsx
- client/src/components/Sidenav.jsx
- client/src/components/SignIn.jsx
- client/src/components/SignUp.css
- client/src/components/SignUp.jsx
- client/src/index.css
This pull request involves refactoring the icon usage across multiple components to use React components instead of image files. This change aims to improve the maintainability and consistency of the icon usage throughout the application.
Icon Refactoring:
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R12): Replaced the `plus-btn.svg` image with the `PlusIcon` component. [[1]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R12) [[2]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L118-R119)
* [`client/src/components/MealGroup.jsx`](diffhunk://#diff-4361ac94da04fb7f0f479b4c925a1a7b35e9e7455201eff0d314bd00c6553c1aR2): Replaced the `circle-dashed-plus.svg` image …
> SCRUM-88 Integrate new Icon components

- client/src/components/Sidenav.jsx
- client/src/icons/CalendarIcon.jsx
- client/src/icons/ChefHatIcon.jsx
This pull request includes several updates to the `Sidenav` component and the addition of new icons in the `client/src/icons` directory. The most important changes include adding new icons, updating the `Sidenav` component to use these icons, and ensuring the navigation links are correctly routed.
* [`client/src/components/Sidenav.jsx`](diffhunk://#diff-cf4686b80d69f6d3f89d133171d85a3e759ebb3752804f8aa21e7f4ab438e577R13-R14): Added imports for `ChefHatIcon` and `CalendarIcon` to the existing list of icons.
* [`client/src/components/Sidenav.jsx`](diffhunk://#diff-cf4686b80d69f6d3f89d133171d85a3e759ebb3752804f8aa21e7f4ab438e577L35-R58): Updated the navigation links to use the new icons and corrected the `href` attributes to ensure proper routing.
* …
> SCRUM-80 Add My Recipes and Generate Meal Plan nav items to the sidebar

- client/src/MealPlanGenerator.jsx
- client/src/Recipes.jsx
This pull request includes several changes to clean up the code in the `MealPlanGenerator` and `Recipes` components by removing unnecessary `console.log` statements and an unused import. 
Code cleanup:
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00L37-L38): Removed unnecessary `console.log` statements used for debugging purposes. [[1]](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00L37-L38) [[2]](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00L54)
* [`client/src/Recipes.jsx`](diffhunk://#diff-5522bc0d0372c2bd2c780343817952584e007f1238ddc798c748dafba0c4bf29L3): Removed an unused import for `page` and unnecessary `console.log` statements used for …
> SCRUM- 97 Remove unnecessary console logs from MealPlanGenerator and Recipes components

- client/src/components/MealGroup.jsx
This pull request includes changes to the `MealGroup` component in the `client/src/components/MealGroup.jsx` file. The most important changes involve restructuring the rendering logic for the `recipes` array to ensure proper key assignment and conditional rendering.
Rendering logic improvements:
* Moved the `key` attribute from the `<li>` element to the `MealCard` component when `applicationContext` is "recipes". This ensures that each `MealCard` has a unique key for React's reconciliation process.
* Corrected the conditional rendering to properly wrap the `input` and `p` elements inside an `<li>` element with the class `picker__item` when `applicationContext` is not "recipes". This ensures consistent structure and styling for the list items. …
> SCRUM-98 Refactor MealGroup component to simplify recipe rendering and improve readability

- client/src/components/Sidenav.jsx
This pull request includes changes to the `Sidenav` component to improve the handling of active navigation links based on the current path. The changes involve setting the current path state and updating the class of navigation links dynamically.
Key changes:
* [`client/src/components/Sidenav.jsx`](diffhunk://#diff-cf4686b80d69f6d3f89d133171d85a3e759ebb3752804f8aa21e7f4ab438e577R19-R37): Added state `currentPath` to store the current path and an effect to update this state on route changes using `page.js`.
* [`client/src/components/Sidenav.jsx`](diffhunk://#diff-cf4686b80d69f6d3f89d133171d85a3e759ebb3752804f8aa21e7f4ab438e577L42-R85): Updated the class of navigation links to include "active" based on the `currentPath` state, ensuring the correct link is highlighted.
> SCRUM-89 Add active link highlighting to Sidenav based on current route

- client/src/MealPlanGenerator.jsx
- client/src/Recipes.jsx
This pull request includes enhancements to the `MealPlanGenerator` and `Recipes` components to improve the user experience by adding loading indicators and better error handling.
Improvements to user experience:
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00R34): Added a loading state that sets `loading` to `true` when fetching recipes and displays a loading message while the data is being fetched. The loading state is set to `false` in the `finally` block of the fetch call. [[1]](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00R34) [[2]](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00L51-R53) …
> SCRUM-99 Integrate loading state with the GET request for fetching recipes in MealPlanGenerator component

- client/src/MealInfo.jsx
- client/src/components/MealCard.jsx
- client/src/utils/mealUtils.js
This pull request refactors the codebase by extracting a utility function and updating its usage across multiple components. The main changes include moving the `getMealLabel` function to a separate utility file and updating the components to use this new utility function.
Refactoring and code reuse:
* [`client/src/MealInfo.jsx`](diffhunk://#diff-dd264326910cb8b5a6d80b7edcf1d011b569b5974af8da2ed13db83ee1df5fa6R4): Imported the `getMealLabel` function from `mealUtils` and replaced the inline logic with a call to this function. [[1]](diffhunk://#diff-dd264326910cb8b5a6d80b7edcf1d011b569b5974af8da2ed13db83ee1df5fa6R4) [[2]](diffhunk://#diff-dd264326910cb8b5a6d80b7edcf1d011b569b5974af8da2ed13db83ee1df5fa6L75-R76)
* [`client/src/components/MealCard.jsx`](diffhunk://#diff-1709d557f9c27c9f122e851 …
> SCRUM-100 Fix mealGroup info in MealInfo component and move getMealLabel util to different file

- client/src/MealInfo.jsx
This pull request includes changes to the `MealInfo` component in `client/src/MealInfo.jsx` to improve code readability and handle potential null or undefined values more gracefully. The most important changes include using optional chaining and nullish coalescing operators, and removing unnecessary fragments.
Code readability and null handling improvements:
* Replaced conditional rendering with optional chaining and nullish coalescing operators for `meal` properties.
* Removed unnecessary React fragments around the main `div` element.
* Simplified the rendering of the image, title, nutrition, ingredients, and instructions by using optional chaining and nullish coalescing operators.
> SCRUM-101 Improve MealInfo component by adding optional chaining and default values for better error handling

- client/src/MealPlanGenerator.css
- client/src/MealPlanGenerator.jsx
- client/src/icons/Shuffle.jsx
This pull request includes several updates to improve the user interface and loading state management in the `MealPlanGenerator` component. The most important changes include adding a new `ShuffleIcon`, updating the loading state variables, and enhancing the button styling.
UI Enhancements:
* [`client/src/MealPlanGenerator.css`](diffhunk://#diff-7a7b0565044d4b893d86a4818618f71aa2ac16545de9f13e57fce07814f9bb41R33-R40): Added new styles for the `.btn-content` class to improve button layout.
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00L228-R239): Updated the button to include a `ShuffleIcon` and improved the button's content layout.
Loading State Management:
* …
> SCRUM-102 Refactor MealPlanGenerator to improve loading state management and enhance button UI with ShuffleIcon

- client/src/components/CreateRecipe.css
- client/src/components/CreateRecipe.jsx
This pull request includes changes to the `CreateRecipe` component to enhance functionality and improve user experience. The main updates involve adding a new select input for meal groups, converting string inputs to integers, and implementing an overlay click handler to close the modal.
Enhancements to `CreateRecipe` component:
* [`client/src/components/CreateRecipe.css`](diffhunk://#diff-ea34ec18fb7cb2ce8bf2f16090046272e6d868106322c1d837e6db6828ec4a8aL36-R37): Added styling for the new `select` input to ensure it matches the existing form elements.
* [`client/src/components/CreateRecipe.jsx`](diffhunk://#diff-f28e439c1e9a1d50f388925191b090686a1a9486e391e179011a4f181c16d901R20-R26): Introduced a new `select` input for meal groups in the form and updated the form submission logic to …
> SCRUM-96 Add meal group selection to CreateRecipe component, refactor input handling, and overlay click handler to close the modal

- server/firebase.json
- server/server.js
- server/storage.rules
This pull request includes several changes to enhance Firebase storage integration and improve image generation functionality in the `server` directory. The most important changes include adding Firebase storage configuration, updating image generation logic, and importing necessary modules.
Enhancements to Firebase storage integration:
* [`server/firebase.json`](diffhunk://#diff-6b79dd0da8301c9849b69d8305ecfe57826a9747db18afc246f87bd985595cb3R9-R18): Added storage configuration with port and rules for Firebase storage.
* [`server/storage.rules`](diffhunk://#diff-675d139cb3b5795db9919ad1dcaa2112525555bb7f208d2f14abc79f05ecd151R1-R7): Added rules to allow authenticated read and write access to Firebase storage.
Improvements to image generation functionality:
* …
> SCRUM-104 Refactor recipe generation to use Gemini experimental image generation and store them in firebase storage

- client/src/constants.js
- client/src/firebase.js
This pull request includes changes to improve the development experience by differentiating between development and production environments for both server URLs and Firebase authentication.
Environment-specific configurations:
* [`client/src/constants.js`](diffhunk://#diff-630b562b2d9daad631d8716bf3c253f6da5223c52c77adba3f8d518775355169L3-R7): Modified `SERVER_URL` to use `localhost` for development and the production URL for production.
* [`client/src/firebase.js`](diffhunk://#diff-874dbf3bc6835048ef48f8e8631b735b4f11a4a32afcd61846f9c26e4fcf535aL2-R6): Added `connectAuthEmulator` to Firebase imports and connected to the Firebase authentication emulator when in development mode. [[1]](diffhunk://#diff-874dbf3bc6835048ef48f8e8631b735b4f11a4a32afcd61846f9c26e4fcf535aL2-R6) …
> SCRUM-108 Configure environment-specific server and emulator settings for development

- client/src/components/SignIn.jsx
- client/src/components/SignUp.css
- client/src/components/SignUp.jsx
- client/src/index.css
This pull request includes several updates to the `SignIn` and `SignUp` components and their associated styles. The main focus is on improving the styling and structure of the forms, as well as ensuring consistency in the design.
* [`client/src/components/SignIn.jsx`](diffhunk://#diff-99e298d84b810ef81687151940075f77f4b9a20e9dec87702f5f2de5bb2eea6cL64-R86): Updated the `SignIn` form to include new class names for email and password containers, and added the `body-s` class to labels, inputs, and buttons for consistent styling. [[1]](diffhunk://#diff-99e298d84b810ef81687151940075f77f4b9a20e9dec87702f5f2de5bb2eea6cL64-R86) [[2]](diffhunk://#diff-99e298d84b810ef81687151940075f77f4b9a20e9dec87702f5f2de5bb2eea6cL103-R109) [[3]](diffhunk://#diff-99e298d84b810ef81687151940075f77f4b9a20e9dec87702f5 …
> SCRUM-110 Refactor SignIn and SignUp components for improved styling and structure

- client/src/Recipes.jsx
This pull request includes changes to the `client/src/Recipes.jsx` file to enhance the recipe deletion functionality and improve user authentication handling. The most important changes include importing the `page` module for navigation, adding error handling, and ensuring proper user authentication during recipe deletion.
Enhancements to recipe deletion functionality:
* [`client/src/Recipes.jsx`](diffhunk://#diff-5522bc0d0372c2bd2c780343817952584e007f1238ddc798c748dafba0c4bf29R3): Imported the `page` module to handle navigation.
* [`client/src/Recipes.jsx`](diffhunk://#diff-5522bc0d0372c2bd2c780343817952584e007f1238ddc798c748dafba0c4bf29R78-R113): Modified the `handleDeleteRecipe` function to include user authentication checks and error handling when deleting a recipe from the server.
> SCRUM-95 Implement recipe deletion with user authentication and error handling

- client/src/Recipes.jsx
- client/src/components/ConfirmationModal.css
- client/src/components/ConfirmationModal.jsx
This pull request introduces a confirmation modal for deleting recipes and refactors the deletion logic in the `MealPlanGenerator` component. The most important changes include adding the `ConfirmationModal` component, updating the deletion logic to use the modal, and adding the necessary CSS for the modal.
* [`client/src/Recipes.jsx`](diffhunk://#diff-5522bc0d0372c2bd2c780343817952584e007f1238ddc798c748dafba0c4bf29R3-R7): Imported `ConfirmationModal` and added state management for the recipe to be deleted. Updated the deletion logic to show the confirmation modal and handle the confirmation or cancellation of the deletion. [[1]](diffhunk://#diff-5522bc0d0372c2bd2c780343817952584e007f1238ddc798c748dafba0c4bf29R3-R7) [[2]](diffhunk://#diff-5522bc0d0372c2bd2c780343817952584e007f1238ddc798c74 …
> SCRUM-105 Refactor delete recipes to show confirm modal after clicking to delete

- client/src/Home.jsx
- client/src/components/EnergySummary.jsx
- client/src/components/TargetSummary.jsx
This pull request includes several improvements and bug fixes to the `Home` component and its associated components in the client-side codebase. The changes primarily focus on handling missing data, improving data fetching, and ensuring default values are set appropriately.
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R28): Added a new state variable `userData` and implemented a `useEffect` hook to fetch user data from the server. This ensures that user data is dynamically loaded and available for use in the component. [[1]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R28) [[2]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R132-R155)
* …
> SCRUM-113 Implement user data fetching

- client/src/MealInfo.jsx
- client/src/components/ProtectedRoute.jsx
This pull request includes changes to improve the user interface by updating the loading indicators in two components.
User interface improvements:
* [`client/src/MealInfo.jsx`](diffhunk://#diff-dd264326910cb8b5a6d80b7edcf1d011b569b5974af8da2ed13db83ee1df5fa6L59-R59): Changed the loading text from a paragraph (`<p>`) to a heading (`<h4>`) to enhance visibility.
* [`client/src/components/ProtectedRoute.jsx`](diffhunk://#diff-b5c96bfce482c6d4c3c46a5b43c08f4ff2cf9d96fab7fbac14a7e3b1292bd6eaL15-R15): Updated the loading text from a div (`<div>`) to a heading (`<h4>`) for consistency and better user experience.
> SCRUM-114 Replace loading message with a header in MealInfo and ProtectedRoute components for improved visibility

- client/public/icons/arrows-exchange.svg
- client/src/Home.jsx
- client/src/components/MealCard.css
- client/src/components/MealCard.jsx
- client/src/components/ReplaceRecipeModal.css
- client/src/components/ReplaceRecipeModal.jsx
- client/src/index.css
This pull request introduces several enhancements and fixes to the `Home` and `MealCard` components, as well as the addition of a new `ReplaceRecipeModal` component. The changes include renaming variables for clarity, updating component props, and adding new styles.
* Renamed `recipes` to `recipeList` in `Home.jsx` for better clarity and updated state management accordingly.
* Added new props (`date`, `allRecipes`, `applicationContext`, `onReplaceRecipeId`) to the `MealCard` component to support recipe replacement functionality. [[1]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R211-R215) [[2]](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66adce1aae3bdfR17-R25)
* Created `ReplaceRecipeModal.jsx` to handle the replacement of …
> SCRUM-106 Allow user to change a meal in their meal plan manually

- server/server.js
This pull request makes changes to the `server/server.js` file, specifically in the handling of date formatting in meal plan endpoints. The changes remove the date formatting step from the `GET` endpoint and modify the date format in the `POST` endpoint to use ISO strings.
Changes to date handling in meal plan endpoints:
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L180-L191): Removed the date formatting step from the `GET /api/meal_plans/:uid` endpoint, simplifying the code by directly adding the date data to the `mealPlans` array without reformatting.
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L335-R323): Updated the `POST /api/generate_meal_plan` endpoint to format …
> SCRUM-118 Refactor date formatting in meal plans API to use ISO string format

- client/src/Home.jsx
- client/src/components/DaySelector.jsx
This pull request includes several changes to the `client/src/Home.jsx` and `client/src/components/DaySelector.jsx` files to improve date handling, update recipe IDs, and enhance the display format for dates. The most important changes include replacing the date formatting logic, updating the recipe ID in meal plans, and modifying the `DaySelector` component to use the new display date format.
Improvements to date handling:
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L21-R25): Replaced the `getFormattedDate` function with a new approach to format dates as `YYYY-MM-DD` using `toISOString` and `split`.
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L42-R58): Updated the …
> SCRUM-116 Refactor date handling in Home component; update DaySelector to display formatted dates

- client/package-lock.json
Reverts jozefntes/meal-plan-gen-app#108
> Revert "Update frontend dependencies"

- client/src/MealPlanGenerator.jsx
- client/src/components/MealGroup.jsx
This pull request includes several changes to the `MealPlanGenerator` and `MealGroup` components to simplify the code and improve functionality. The most important changes include passing the `mealGroup` and `selectedRecipes` properties to `MealGroup`, and modifying the key and id attributes to include the `mealGroup` for better identification.
Improvements to `MealPlanGenerator`:
* [`client/src/MealPlanGenerator.jsx`](diffhunk://#diff-7272077c0bff68b90c7458e87ee151d33b921ed523b60273bc4a7fb25ab2bb00L178-R206): Simplified the `recipes` prop by passing the entire `recipes` array and filtering within the `MealGroup` component. Added `mealGroup` and `selectedRecipes` props to each `MealGroup` instance.
Enhancements to `MealGroup`:
* [`client/src/components/MealGroup.jsx`](diffhunk://#diff-4361 …
> SCRUM-129 Remove mealGroup functionality to MealPlanGenerator page

- client/src/components/MealCard.css
- client/src/index.css
This pull request includes several CSS changes to improve the layout and text handling in the `MealCard` component and to prevent horizontal overflow on the entire page.
Changes to `MealCard` component:
* [`client/src/components/MealCard.css`](diffhunk://#diff-7cc01bb6755947228f64cbb05e6d7d085576346c6f3beb8bd4aa593830a0c48eL8-R8): Adjusted the `meal-card` class to use fixed height and width instead of minimum dimensions.
* [`client/src/components/MealCard.css`](diffhunk://#diff-7cc01bb6755947228f64cbb05e6d7d085576346c6f3beb8bd4aa593830a0c48eR54-R63): Added styling to the `meal-info p` selector to limit text to three lines and handle overflow with ellipsis.
Global styling changes:
* [`client/src/index.css`](diffhunk://#diff-9ba564eb566d9d518337365ff59440cd64b7217d0ddb75f1c2524003735b99adR66 …
> SCRUM-134 Fix MealCard dimensions and enhance text overflow handling; prevent horizontal scroll on body

- client/src/components/CreateRecipe.css
- client/src/components/CreateRecipe.jsx
This pull request updates the `CreateRecipe` component by improving its styling, enhancing accessibility, and refactoring the ingredient selection logic. The most important changes include introducing a new `.checkbox-wrapper` class for better checkbox styling, replacing labels with div wrappers for ingredient checkboxes, and updating CSS to use variables for consistent theming.
* Updated `.ingredient-list` and `.checkbox-label` styles to use CSS variables (`--background-color`, `--component-bg`) for consistent theming and added flexbox properties for better alignment. [[1]](diffhunk://#diff-ea34ec18fb7cb2ce8bf2f16090046272e6d868106322c1d837e6db6828ec4a8aL76-R100) [[2]](diffhunk://#diff-ea34ec18fb7cb2ce8bf2f16090046272e6d868106322c1d837e6db6828ec4a8aR109-R140)
* Introduced a new …
> SCRUM-125 Fix dark mode styling in ingredients dropdown

- server/server.js
This pull request introduces a new API endpoint to handle user data creation in the `server.js` file. The most important change is the addition of a POST route for saving user details, including validation and error handling.
* Added a new POST route at `/api/users` to save user details (`uid`, `name`, `age`, `height`, `currentWeight`, `goalWeight`, `fitnessGoal`, `dietaryPreferences`). This route includes:
- Validation to ensure all required fields are provided and that `fitnessGoal` is within the valid range (1–3).
- Authorization check to ensure the `uid` in the request matches the authenticated user's `uid`.
- Database interaction to save user details to the `users` collection in Firestore, with a `createdAt` timestamp.
- Error handling for invalid input, authorization failures, and …
> SCRUM-135 Add POST /api/users that allows the user to save their data

- client/src/App.jsx
- client/src/Profile.css
- client/src/Profile.jsx
- client/src/components/Sidenav.jsx
Created Profile Page: Profile.jsx and Profile.css
> Added Profile Page

- client/src/Profile.css
- client/src/Profile.jsx
- client/src/index.css
This pull request refactors the `Profile` component by cleaning up unused styles, improving code readability, and updating the design system. It removes redundant CSS, refines JSX structure, and updates some design tokens for better consistency.
* Renamed `.generate-page` to `.profile-page` and removed unused styles such as `.profile-picture`, `.progress-bar`, and `.btn-outline` from `Profile.css`. This reduces unnecessary CSS and aligns styles with the updated design. [[1]](diffhunk://#diff-1ab2ba713473dbfb8f09678a59067a5086307ffd7b9ca99a66b52ae934d444fcL1-R1) [[2]](diffhunk://#diff-1ab2ba713473dbfb8f09678a59067a5086307ffd7b9ca99a66b52ae934d444fcL12-L54) [[3]](diffhunk://#diff-1ab2ba713473dbfb8f09678a59067a5086307ffd7b9ca99a66b52ae934d444fcL85-L90) …
> SCRUM-138 Refactor Profile component styles and update CSS variables

- client/src/Home.jsx
- client/src/index.css
This pull request refactors the `Home` component in `client/src/Home.jsx` to simplify and streamline the calculation of nutritional progress. The key changes include removing redundant code for progress calculations and improving the readability of existing logic.
* Simplified the `reduce` logic for calculating energy and protein percentages by formatting the callback function for better readability. [[1]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L94-R95) [[2]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L108-R110)
* Removed the previously defined `progress` object, which redundantly calculated nutritional metrics (energy, fat, carbs, and protein). This simplifies the code and avoids unnecessary computations.
> SCRUM-139 Remove meal progress unused variable

- server/server.js
This pull request adds a new API endpoint to update the completion status of a meal in a user's meal plan. The most important change is the addition of the `PATCH /api/meal_done` route, which includes validation, authorization, and database interaction logic.
* **`PATCH /api/meal_done` route in `server/server.js`:**
- Added an endpoint to update the `done` status of a meal in a user's meal plan.
- Includes validation to ensure all required fields (`uid`, `date`, `mealId`, `done`) are provided and that `done` is a boolean.
- Implements authorization to ensure the user can only modify their own meal plans.
- Handles errors for missing meal plans, invalid meal plan formats, and meals not found in the plan.
- Updates the meal's `done` status in the database and merges the changes into the …
> SCRUM-137 Add endpoint to update meal status in meal plan

- server/server.js
This pull request introduces changes to enhance the handling of meal plans by adding a unique `mealInstanceId` for each meal instance. This ensures better identification of meals across different operations and improves data consistency. The changes primarily affect the generation of meal plans, replacement of recipes, and marking meals as done.
* In `app.post("/api/generate_meal_plan")`: Added a `mealInstanceId` property to each meal, constructed using the meal's `id`, its index, and the associated date. This ensures each meal instance has a unique identifier.
* In `app.post("/api/replace_recipe")`: Updated the logic to replace a meal by assigning a new `mealInstanceId` when a recipe is replaced. This ensures the updated meal instance is uniquely identified.
* In …
> SCRUM-143 Enhance meal plan and recipe management by adding mealInstanceId for unique identification

- client/src/components/MealCard.jsx
- client/src/components/RecipeGrid.css
This pull request introduces improvements to the `MealCard` component to handle missing or broken image URLs gracefully, as well as updates to the `RecipeGrid` CSS for better spacing and styling. Below are the key changes:
* Added a `backgroundImage` state and a fallback mechanism to handle missing or broken image URLs using a placeholder image (`/images/placeholder.webp`). This includes the `handleImageError` function to update the background image on error. (`client/src/components/MealCard.jsx`, [client/src/components/MealCard.jsxL23-R39](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66adce1aae3bdfL23-R39))
* Included a hidden `<img>` element for preloading the image and detecting errors, triggering the fallback mechanism when necessary. …
> SCRUM-140 Refactor MealCard component to handle image loading errors and update background image logic

- client/src/Home.jsx
- client/src/components/MealCard.jsx
This pull request introduces changes to enhance the handling of `mealInstanceId` in the meal planning feature. The updates ensure that each meal instance has a unique identifier, improving data consistency and enabling rollback functionality in case of errors. Below are the most important changes grouped by theme:
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L152-R177): Updated the `updateRecipeId` function to generate and assign a unique `mealInstanceId` for each meal when replacing a recipe. The function now returns the newly generated `mealInstanceId` for further use.
* [`client/src/components/MealCard.jsx`](diffhunk://#diff-1709d557f9c27c9f122e851a87a1f4d7aeeb303243f5dec81d66adce1aae3bdfL59-R59): Modified the optimistic UI …
> SCRUM-146 Refactor updateRecipeId and MealCard to handle mealInstanceId updates and rollback on error

- client/public/icons/chevron-left-white.svg
- client/src/MealInfo.css
- client/src/MealInfo.jsx
This pull request introduces a "Back" button to the `MealInfo` component, allowing users to navigate back to the "My Recipes" page. The changes include styling for the button and its integration into the component.
* **Added a "Back" button with hover effects**: A new `.back-btn` class was introduced in `client/src/MealInfo.css` to style the button, including positioning, size, hover effects, and transitions for a polished user experience.
* **Integrated the "Back" button into the `MealInfo` component**: The button was added to `MealInfo.jsx` with functionality to navigate to the "My Recipes" page when clicked, using the `page` function. It also includes an icon for visual clarity.
> SCRUM-149 Add back button to MealInfo component with chevron icon

- client/public/icons/search.svg
- client/src/Home.css
- client/src/Home.jsx
- client/src/Recipes.jsx
This pull request introduces a search functionality for recipes and makes related UI and logic updates across the `Home` and `Recipes` components. The most significant changes include adding a search bar to the `Home` page, implementing search query handling and filtering logic in the `Recipes` page, and updating styles to accommodate the new UI elements.
* Added a search bar to the `Home` page, allowing users to input a search query and navigate to the `Recipes` page with the query as a URL parameter. This includes a new `handleSearch` function and a `searchQuery` state in `Home.jsx`. (`client/src/Home.jsx`, [[1]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R33) [[2]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R80- …
> SCRUM-150 Add search functionality to Home and Recipes components

- client/src/Home.css
- client/src/Home.jsx
- client/src/components/MealGroup.css
This pull request introduces a new "Ingredient List" feature to the `Home` page and includes associated styling updates. The changes focus on enhancing the user interface by adding a structured ingredient list for selected meals and improving the visual presentation.
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33R499-R514): Added a new `home-ingredient-list` section to display ingredients for selected meals. The list is dynamically generated using a combination of meal and ingredient data.
* [`client/src/Home.css`](diffhunk://#diff-3b1a9da07623e6c614d6f215bddee90c945a731e686938b8b0009b5523e3bf9dR49-R69): Added styles for the new `home-ingredient-list`, including layout, spacing, and grid-based item organization.
* …
> SCRUM-151 Add ingredients list for the day to Home page

- client/src/MealInfo.jsx
- client/src/components/ReplaceRecipeModal.jsx
This pull request includes small updates to improve user navigation and clean up unused code in the `MealInfo` and `ReplaceRecipeModal` components.
Navigation improvement:
* [`client/src/MealInfo.jsx`](diffhunk://#diff-dd264326910cb8b5a6d80b7edcf1d011b569b5974af8da2ed13db83ee1df5fa6L62-R62): Updated the "Back" button to use `window.history.back()` instead of navigating to a specific route, providing a more intuitive user experience.
Code cleanup:
* [`client/src/components/ReplaceRecipeModal.jsx`](diffhunk://#diff-f6dd4e38cc7434f86d95847190a5d66a0cc0f9aa95a9bb823ea807a6cf5ad2b6L7): Removed the unused `mealGroup` prop from the `ReplaceRecipeModal` component to simplify the code.
> SCRUM-152 Update back button functionality in MealInfo and remove unused mealGroup prop in ReplaceRecipeModal

- client/src/components/ReplaceRecipeModal.jsx
This pull request updates the `ReplaceRecipeModal` component to enhance its functionality and improve the user experience. The most important changes include modifying the filtering logic for recipes based on the search query and updating the messaging displayed when no recipes are found.
* Updated the recipe filtering logic to prioritize the `searchQuery` input. If a search query is provided, all recipes are filtered based on the query; otherwise, the filtering defaults to `similarRecipes`. (`client/src/components/ReplaceRecipeModal.jsx`, [client/src/components/ReplaceRecipeModal.jsxL47-R51](diffhunk://#diff-f6dd4e38cc7434f86d95847190a5d66a0cc0f9aa95a9bb823ea807a6cf5ad2b6L47-R51))
* Enhanced the "no recipes found" messaging. If no recipes match the search query, a general message is …
> SCRUM-153 Refactor recipe filtering logic in ReplaceRecipeModal to prioritize search query and update no recipes found message

- client/src/Profile.css
- client/src/Profile.jsx
This pull request includes updates to the `Profile` component and its associated CSS to improve code readability, consistency, and maintainability. The changes include renaming CSS classes for better specificity, improving code formatting, and ensuring consistent use of quotation marks in JavaScript.
* Renamed `.progress-bar` to `.profile-progress-bar` and `.progress-fill` to `.profile-progress-fill` for better specificity and alignment with the `Profile` component. [[1]](diffhunk://#diff-1ab2ba713473dbfb8f09678a59067a5086307ffd7b9ca99a66b52ae934d444fcL59-R66) [[2]](diffhunk://#diff-abb97b9095c17a91eca821b681d553cb0631397d5000484e3c87ad13163f0aadL388-R396)
* Updated `fetch` request headers to use consistent double quotes for key names in `Profile.jsx`.
* Reformatted conditional …
> SCRUM-154 Rename progress bar classes for consistency in Profile component

- server/server.js
This pull request introduces improvements to code readability, validation logic, and minor cleanup in the `server/server.js` file. The changes focus on enhancing maintainability and ensuring stricter input validation.
* Refactored the mapping and filtering logic for associating recipes with meal groups (`breakfastRecipes`, `lunchRecipes`, `dinnerRecipes`, `snackRecipes`) by formatting the code for better readability.
* Added stricter validation for `minProtein`, `maxCarbs`, and `maxFat` in the `/api/generate_recipe` endpoint to ensure the values fall within acceptable ranges.
* Removed an unnecessary blank line in the `/api/meal_done` endpoint to maintain consistent formatting.
> SCRUM-155 Validate nutritional parameters in generate_recipe endpoint for improved input handling

- server/server.js
This pull request updates the `server.js` file to enhance the user creation endpoint (`/api/users`) with more detailed user input validation and the calculation of personalized energy and macronutrient targets. Additionally, it simplifies error handling in the recipe generation endpoint (`/api/generate_recipe`).
* **Expanded User Input Fields**: Added new fields `gender`, `baselineActivity`, and `weightGoalRate` while removing `fitnessGoal` from the request body. These fields are now required for user creation. (`[[1]](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R584-R589)`, `[[2]](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R598-L610)`)
* **Basal Metabolic Rate (BMR) and Activity Adjustment**: Implemented BMR …
> SCRUM-157 Refactor user creation endpoint to include gender and baseline activity; calculate BMR and energy targets based on user inputs

- client/src/Profile.jsx
This pull request introduces significant updates to the `Profile.jsx` file, enhancing the user profile management functionality. The changes include replacing the fitness goals feature with a weight goal rate, adding new fields for gender and activity level, and improving the edit mode functionality with a cancel button. Additionally, helper functions were added to map values to user-friendly labels.
* Added new fields for `gender`, `activityLevel`, and `weightGoalRate` to the profile form. These fields are now part of the `formData` state and are displayed in both edit and view modes. [[1]](diffhunk://#diff-abb97b9095c17a91eca821b681d553cb0631397d5000484e3c87ad13163f0aadR7-R67) [[2]](diffhunk://#diff-abb97b9095c17a91eca821b681d553cb0631397d5000484e3c87ad13163f0aadR96-R105) …
> SCRUM-156 Add gender and activity level selection to profile form; implement goal rate options

- client/src/Profile.css
- client/src/Profile.jsx
This pull request includes updates to the `Profile` component and its associated styles to improve naming consistency, enhance dropdown functionality, and fix minor UI issues. The most important changes include renaming `goalRate` to `weightGoalRate` for clarity, adding a new `.dropdown` class for styling, and improving the user experience for dropdown menus.
* Renamed `goalRate` to `weightGoalRate` across the `Profile.jsx` file to improve clarity and align with the data model. This change affects variable names, function parameters, and form field bindings. [[1]](diffhunk://#diff-abb97b9095c17a91eca821b681d553cb0631397d5000484e3c87ad13163f0aadL7-R8) [[2]](diffhunk://#diff-abb97b9095c17a91eca821b681d553cb0631397d5000484e3c87ad13163f0aadL105-R105) …
> SCRUM-158 Refactor Profile component to standardize weight goal rate handling and enhance dropdown styling

- server/server.js
This pull request introduces a new utility function, `generateSignedUrl`, to centralize the logic for generating signed URLs for accessing files. It also refactors existing code to use this new function, improving maintainability and reducing duplication.
* Added `generateSignedUrl` in `server/server.js` to generate signed URLs for files stored in the bucket. This function handles URL generation with a 1-hour expiration and includes error handling.
* Refactored the `/api/recipes/:uid` endpoint to use `generateSignedUrl` when adding the `image` property to recipe objects, ensuring consistency and reducing code duplication.
* Updated the `/api/generate_recipe` endpoint to replace inline signed URL generation with the `generateSignedUrl` function, improving reusability and maintainability.
> SCRUM-159 Add generateSignedUrl function and update recipe fetching to include signed URLs for images

- client/src/App.jsx
- client/src/Home.jsx
- client/src/MealPlanGenerator.jsx
- client/src/Recipes.jsx
- client/src/components/ReplaceRecipeModal.jsx
This pull request introduces significant changes to the recipe management system, focusing on centralizing recipe data handling, improving state management, and enhancing user experience. The key updates involve moving recipe fetching logic to the `App` component, passing recipes as props to child components, and refining error handling and UI messages.
* Moved recipe fetching logic to the `App` component, utilizing Firebase authentication to fetch user-specific recipes from the server and manage loading and error states. Recipes are now passed as props to `Home`, `MealPlanGenerator`, and `Recipes` components. (`client/src/App.jsx`: [[1]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR21-R74) [[2]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead377 …
> SCRUM-160 Implement user authentication and recipe fetching in App component

- client/src/Home.jsx
This pull request refines the `Home` component in `client/src/Home.jsx` by improving the logic for calculating meal progress and ensuring better handling of dependencies in the `useEffect` hook. The changes primarily focus on code readability, correctness, and dynamic updates.
* Enhanced the readability of `reduce` operations for calculating `energy`, `protein`, and `carbs` progress by properly formatting the callback function across multiple lines. [[1]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L313-R324) [[2]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L335-R340) [[3]](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9fc33L355-R361)
* Added a conditional check in the `useEffect` hook …
> SCRUM-161 Enhance meal progress calculation by adding userData dependency and ensuring proper handling of selected day records

- server/server.js
This pull request includes a small but meaningful change to enhance the clarity of the image generation request in `server/server.js`. The change updates the description for generating recipe images to specify that the image should be "realistic."
* [`server/server.js`](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L477-R477): Updated the `contents` variable in the `/api/generate_recipe` endpoint to specify "Generate a realistic image of" instead of "Generate an image of" for improved clarity in image generation requests.
> SCRUM-164 Enhance image generation prompt for recipe to specify realism

- client/src/App.jsx
This pull request refines error handling in the `App` component to improve user feedback and handle specific scenarios more gracefully.
* Updated the conditional logic in `App.jsx` to handle a `404` status code specifically by clearing the recipes list (`setRecipes([])`) before proceeding with general error handling.
* Adjusted the error handling block to avoid logging errors redundantly when the error message is "Failed to fetch recipes," ensuring cleaner console output.
> SCRUM-165 Handle recipe fetch errors more gracefully and clear recipes on 404 response

- client/src/App.jsx
- client/src/Home.jsx
- client/src/MealInfo.jsx
This pull request removes redundant comments from several React components in the `client/src` directory to improve code readability and maintainability. The comments removed were primarily stating the obvious or describing self-explanatory code.
* [`client/src/App.jsx`](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aL32): Removed comments explaining authentication state listener setup, handling of unauthenticated users, and cleanup of the listener on component unmount. [[1]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aL32) [[2]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aL63-L69)
* [`client/src/Home.jsx`](diffhunk://#diff-16c5178313a2084c1cc41398cb29a48b21ffe152dfd3726edc3e637e2cd9 …
> SCRUM-166 Remove unnecessary comments and clean up code in App, Home, and MealInfo components

- server/server.js
This pull request refactors and enhances the meal plan and recipe generation functionality in `server/server.js`. It introduces reusable utility functions, improves error handling, and adds a backup model for generating meal plans and recipes when the primary model fails.
* Added `populateAndSaveMealPlan` to handle the population and saving of meal plans, consolidating repetitive logic. [[1]](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R96-R191) [[2]](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L365-R484)
* Added `generateAndSaveRecipe` to streamline recipe generation, image creation, and database saving. [[1]](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R96-R191) …
> SCRUM-167 Add backup model support and improve error handling

- server/server.js
This pull request refactors the meal plan generation logic in `server/server.js` to enhance date handling, improve clarity, and align with updated data structures. The key changes include modifying the `populateAndSaveMealPlan` function to support dynamic date calculations, updating the meal plan prompt schema, and fixing inconsistencies in date handling.
* Updated the `populateAndSaveMealPlan` function to calculate dates dynamically based on a `weekStartDate` parameter, replacing the previous static mapping logic. This ensures accurate date assignment for each day in the meal plan. (`[server/server.jsL96-R110](diffhunk://#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938L96-R110)`)
* Adjusted the calculation of `weekStartDate` to properly handle UTC dates, ensuring …
> SCRUM-168 Refactor meal plan population to use week start date and update prompt structure

- client/src/components/MealGroup.jsx
This pull request introduces a minor UI enhancement to the `MealGroup` component by adding a title section with a description.
UI enhancement:
* [`client/src/components/MealGroup.jsx`](diffhunk://#diff-4361ac94da04fb7f0f479b4c925a1a7b35e9e7455201eff0d314bd00c6553c1aR14-R17): Added a new `div` with the class `meal-group-title` containing the `title` and a description ("Choose 2-3 meals") to improve the visual clarity of the meal group section.
> SCRUM-169 Add Meal Group title directions
